### PR TITLE
Fixed the problems, as with Ygames1

### PR DESCRIPTION
**Pull request by pokmon987**
Alright, basically fixed what Ygames also did, but he did miss "OSSpefic"

### CODE REVIEW

**Comment by pokmon987** [comment]
Oh, and sorry, I accidentally used some of the old code that I wrote and your some of the descriptions were changed

**Comment by Ygames1** [comment]
I already fixed the <osspefic> @pokmon987

**Comment by pokmon987** [comment]
@Ygames1 I looked at your code and saw that instead of OSSpecific it said OSSpefic

**Comment by pokmon987** [comment]
There are also problems with the dot matrix printer with dependencies and from statements

**Comment by Ygames1** [comment]
For someone reason it didnt update in my repo but in the pullrequest its fixed ;P

**Comment by KingNero6** [comment]
Hey I am turning the mod over to you because I have tried your suggestions to get it to work. I have spent 5 days on my own trying to get this fucker to work. I do not have the time to invest in this kind of sink. I have to develope ten assets and finish a river by the end of the month for my game.

**Comment by pokmon987** [comment]
Erm, okay. I'm not exactly sure which error you were exactly referring to, but I did get mine to work fine. Anyways, good luck on your game!

**Comment by KingNero6** [comment]
Thanks it must be a bug on my end then

**Comment by KingNero6** [comment]
Well I figured out what happened and I opened an issue if y'all could be so kind as to take a look for me.

**Pull request merged**
